version: '3'
services:
  server:
    build: .
    ports:
      - "8000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
    restart: always
    command: gunicorn -c gunicorn.conf.py main:app
