version: '3'
services:
  web:
    build: .
    ports:
      - "8000:5000"
    environment:
      FLASK_APP: main.py
      FLASK_ENV: production
    restart: always
    command: gunicorn -c gunicorn.conf.py main:app
    volumes:
      - staticfile:/app/app/static

  nginx:
    build: ./nginx
    ports:
    - "7777:80"
    links:
      - web
    volumes:
      - staticfile:/staticfile

volumes:
  staticfile: